[
  ./foot.nix
  ./btop/btop.nix
  ./rofi/rofi.nix
  ./dunst/dunst.nix
  ./cava.nix
  ./notification.nix
  ./music.nix
  ./search.nix
  ./yt-dlp.nix
  ./mpv/mpv.nix
  ./imgview.nix
  ./lazygit.nix
  ./neofetch/neofetch.nix
  ./firefox/firefox.nix
  ./zathura/zathura.nix
  ./ranger/ranger.nix
  ./fcitx5/fcitx5-theme.nix
  ./weston/weston.nix
]
