[
  ./foot.nix
  ./btop/btop.nix
  ./rofi/rofi.nix
  ./dunst/dunst.nix
  ./cava.nix
  ./notification.nix
  ./music.nix
  ./search.nix
  ./mpv/mpv.nix
  ./imgview.nix
  ./lazygit.nix
  ./neofetch/neofetch.nix
  ./firefox/firefox.nix
  ./weston/weston.nix
  ./vscode.nix
  ./gitkraken.nix
]
